<a href="https://colab.research.google.com/github/thisisarjun100905/repo1/blob/main/RLproject1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy  as np
import pandas as pd
import random

In [2]:
rewards = np.array([
    [-1 , -1 , -1 , -1 , 0 , -1],
    [-1 , -1 , -1 , 0 , -1 , 100],
    [-1 , -1 , -1 , 0 , -1, -1],
    [-1 , 0 , 0, -1 , 0 , -1],
    [0 , -1 , -1 , 0, -1 , -1],
    [-1 , 0 , -1 , -1 , -1 , -1],
])

In [3]:
rewards

array([[ -1,  -1,  -1,  -1,   0,  -1],
       [ -1,  -1,  -1,   0,  -1, 100],
       [ -1,  -1,  -1,   0,  -1,  -1],
       [ -1,   0,   0,  -1,   0,  -1],
       [  0,  -1,  -1,   0,  -1,  -1],
       [ -1,   0,  -1,  -1,  -1,  -1]])

In [4]:
pd.DataFrame(rewards)

0  1  2  3  4    5
0 -1 -1 -1 -1  0   -1
1 -1 -1 -1  0 -1  100
2 -1 -1 -1  0 -1   -1
3 -1  0  0 -1  0   -1
4  0 -1 -1  0 -1   -1
5 -1  0 -1 -1 -1   -1

In [7]:
def initial_q(m , n):
  return np.zeros((m , n))

In [8]:
q_matrix = initial_q(6,6)
pd.DataFrame(q_matrix)

0    1    2    3    4    5
0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0  0.0  0.0  0.0

In [10]:
def set_initial_state(rooms = 6):
    return np.random.randint(0 , rooms)


def get_action(current_state , reward_matrix):
      #Given a state , chose from the possible action
    valid_action = []
    for action in enumerate(reward_matrix[current_state]):
        if action[1]!=-1:
          valid_action+=[action[0]]
    return random.choice(valid_action)

In [12]:
def take_action(current_state , reward_matrix , gamma , verbose=False):
    # Take a single action
    action = get_action(current_state , reward_matrix)
    sa_reward = reward_matrix[current_state , action]
    ns_reward = max(q_matrix[action , ]) #next state-action reward
    print(ns_reward)
    q_current_state = sa_reward + (gamma*ns_reward)
    q_matrix[current_state , action]= q_current_state
    new_state = action
    if verbose:
      print(q_matrix)
      print(f"Old State :{current_state} | New State : {new_state}\n\n")
      if new_state==5:
         print(f"Agent has reached it's goal!")
    return new_state

In [13]:
def intitialize_episode(reward_matrix , initial_state , gamma , verbose = False):
    current_state = initial_state
    while True :
      current_state = take_action(current_state , reward_matrix , gamma , verbose)
      if current_state==5:
        break

def train_agent(iterations , reward_matrix , gamma , verbose = False):

    print("Training in Progress")
    for episode in range(iterations):
        initial_state = set_initial_state()
        intitialize_episode(reward_matrix , initial_state , gamma , verbose)

    print("Training Complete !")
    return q_matrix
def normalize_matrix(q_matrix):
    normalized_q = q_matrix/max(q_matrix[q_matrix.nonzero()])*100
    return normalized_q.astype(int)



In [16]:
# Test run of single episode
gamma = 0.1
initial_state = set_initial_state()
initial_action = get_action(initial_state , rewards )
intitialize_episode(rewards , initial_state , gamma , True)

0.0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old State :0 | New State : 4


0.0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old State :4 | New State : 0


0.0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old State :0 | New State : 4


0.0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old State :4 | New State : 3


0.0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old State :3 | New State : 2


0.0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old State :2 | New State : 3


0.0
[[0. 0. 0. 0. 0. 0.]
 [0

In [18]:
# Test run of full training (training = 1000 iterations)
gamma = 0.8
initial_state = set_initial_state()
intial_action = get_action(initial_state ,rewards)
q_table = train_agent(1000 , rewards , gamma , False)

pd.DataFrame(q_table)

Streaming output truncated to the last 5000 lines.
277.7777777777777
222.22222222222217
222.22222222222217
277.7777777777777
222.22222222222217
222.22222222222217
177.77777777777774
222.22222222222217
177.77777777777774
142.2222222222222
177.77777777777774
222.22222222222217
177.77777777777774
222.22222222222217
277.7777777777777
222.22222222222217
177.77777777777774
222.22222222222217
177.77777777777774
142.2222222222222
177.77777777777774
142.2222222222222
177.77777777777774
142.2222222222222
177.77777777777774
142.2222222222222
177.77777777777774
142.2222222222222
177.77777777777774
222.22222222222217
277.7777777777777
222.22222222222217
277.7777777777777
222.22222222222217
177.77777777777774
222.22222222222217
177.77777777777774
222.22222222222217
177.77777777777774
222.22222222222217
177.77777777777774
142.2222222222222
177.77777777777774
142.2222222222222
177.77777777777774
142.2222222222222
177.77777777777774
222.22222222222217
277.7777777777777
222.22222222222217
177.7777777777

0           1           2           3           4           5
0    0.000000    0.000000    0.000000    0.000000  142.222222    0.000000
1    0.000000    0.000000    0.000000  177.777778    0.000000  277.777778
2    0.000000    0.000000    0.000000  177.777778    0.000000    0.000000
3    0.000000  222.222222  142.222222    0.000000  142.222222    0.000000
4  113.777778    0.000000    0.000000  177.777778    0.000000    0.000000
5    0.000000  222.222222    0.000000    0.000000    0.000000    0.000000

In [19]:
pd.DataFrame(normalize_matrix(q_table))

0   1   2   3   4    5
0   0   0   0   0  51    0
1   0   0   0  64   0  100
2   0   0   0  64   0    0
3   0  80  51   0  51    0
4  40   0   0  64   0    0
5   0  80   0   0   0    0

In [20]:
def deploy_agent(init_State , q_table):
  print("Start :", init_State)
  state = init_State
  steps = 0
  while True :
    steps+=1
    action = np.argmax(q_table[state , :])
    print(action)
    state = action
    if action ==5 :
      print("Finishe")
      return steps

In [22]:
start_room =4
step = deploy_agent(start_room , q_table)
print("NUMber of action :" , step)

Start : 4
3
1
5
Finishe
NUMber of action : 3
